services:
  kafka:
    image: apache/kafka:4.0.0
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS=localhost:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - 7869:7869
  #   volumes:
  #     - ./ollama:/root/.ollama
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=4h
  #     - OLLAMA_HOST=0.0.0.0
  langchain:
    image: kwonghung/langchain-as-rest-backend
    container_name: langchain
    build:
      context: langchain-backend

    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    depends_on:
      - kafka
